export const abilities = {
  // Gen III
  "Air Lock": "Eliminates the effects of weather.",
  "Arena Trap": "Prevents non-Flying-type opposing Pokémon from fleeing.",
  "Battle Armor": "Protects the Pokémon from critical hits.",
  "Blaze": "Powers up Fire-type moves when the Pokémon's HP is low.",
  "Cacophony": "The Pokémon is immune to sound-based moves.",
  "Chlorophyll": "Boosts the Pokémon's Speed stat in harsh sunlight.",
  "Clear Body": "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.",
  "Cloud Nine": "Eliminates the effects of weather.",
  "Color Change": "The Pokémon's type becomes the type of the move used on it.",
  "Compound Eyes": "Boosts the Pokémon's Accuracy stat.",
  "Cute Charm": "Contact with the Pokémon may cause infatuation.",
  "Damp": "Prevents the use of Explosion and Self-Destruct.",
  "Drizzle": "Activates rain when the Pokémon enters battle.",
  "Drought": "Activates harsh sunlight when the Pokémon enters battle.",
  "Early Bird": "The Pokémon awakens twice as fast from sleep.",
  "Effect Spore": "Contact with the Pokémon may inflict poison, sleep, or paralysis on its attacker.",
  "Flame Body": "Contact with the Pokémon may inflict burn the attacker.",
  "Flash Fire": "Powers up the Pokémon's Fire-type moves if hit by a Fire-type move.",
  "Forecast": "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.",
  "Guts": "Boosts the Pokémon's Attack stat when it has a status condition.",
  "Huge Power": "Doubles the Pokémon's Attack stat.",
  "Hustle": "Boosts the Pokémon's Attack stat but lowers the Pokémon's Accuracy stat.",
  "Hyper Cutter": "The Pokémon's Attack stat cannot be lowered by other Pokémon.",
  "Illuminate": "Raises the likelihood of meeting wild Pokémon outside of battle.",
  "Immunity": "The Pokémon cannot be poisoned.",
  "Inner Focus": "The Pokémon cannot flinch.",
  "Insomnia": "The Pokémon cannot sleep.",
  "Intimidate": "When the Pokémon enters battle, it lowers opposing Pokémon's Attack stats.",
  "Keen Eye": "The Pokémon's Accuracy stat cannot be lowered by other Pokémon.",
  "Levitate": "The Pokémon is immune to Ground-type moves and Abilities.",
  "Lightning Rod": "The Pokémon draws in all Electric-type moves. Instead of receiving damage by Electric-type moves, it boosts the Pokémon's Sp. Atk.",
  "Limber": "The Pokémon cannot be paralyzed.",
  "Liquid Ooze": "HP draining moves used on the Pokémon damage instead of heal.",
  "Magma Armor": "The Pokémon cannot be frozen.",
  "Magnet Pull": "Prevents Steel-type opposing Pokémon from fleeing.",
  "Marvel Scale": "Boosts the Pokémon's Defense stat when it has a status condition.",
  "Minus": "Boosts the Pokémon's Sp. Atk if an ally with the Plus or Minus Ability is also in battle.",
  "Natural Cure": "The Pokémon loses any status condition after switching out.",
  "Oblivious": "The Pokémon cannot be infatuated or taunted.",
  "Overgrow": "Powers up Grass-type moves when the Pokémon's HP is low.",
  "Own Tempo": "The Pokémon cannot be confused.",
  "Pickup": "The Pokémon may pick up the item an opposing Pokémon used during a battle. The Pokémon may also pick up items outside of battle.",
  "Plus": "Boosts the Pokémon's Sp. Atk if an ally with the Plus or Minus Ability is also in battle.",
  "Poison Point": "Contact with the Pokémon may poison the attacker.",
  "Pressure": "Raises opposing Pokémon's PP usage.",
  "Pure Power": "Doubles the Pokémon's Attack stat.",
  "Rain Dish": "The Pokémon gradually regains HP in rain.",
  "Rock Head": "Protects the Pokémon from recoil damage.",
  "Rough Skin": "Contact with the Pokémon will damage the attacker.",
  "Run Away": "Enables a sure getaway from wild Pokémon.",
  "Sand Stream": "Activates sandstorm when the Pokémon enters battle.",
  "Sand Veil": "Boosts the Pokémon's Evasion stat in a sandstorm.",
  "Serene Grace": "Boosts the likelihood of additional effects occurring when attacking.",
  "Shadow Tag": "Prevents opposing Pokémon from fleeing.",
  "Shed Skin": "The Pokémon may heal its status condition.",
  "Shell Armor": "Protects the Pokémon from critical hits.",
  "Shield Dust": "Protects the Pokémon from additional effects.",
  "Soundproof": "The Pokémon is immune to sound-based moves.",
  "Speed Boost": "The Pokémon's Speed stat is boosted every turn.",
  "Static": "Contact with the Pokémon may paralyze the attacker.",
  "Stench": "Lowers the likelihood of meeting wild Pokémon outside of battle. The Pokémon may also cause a Pokémon to flinch after attacking it.",
  "Sticky Hold": "The Pokémon's item cannot be removed.",
  "Sturdy": "The Pokémon is immune to one-hit KO moves. The Pokémon cannot be knocked out with one hit while at full health either.",
  "Suction Cups": "The Pokémon cannot be forced to switch out or flee.",
  "Swarm": "Powers up Bug-type moves when the Pokémon's HP is low.",
  "Swift Swim": "Boosts the Pokémon's Speed stat in rain.",
  "Synchronize": "The attacker will receive the same status condition if it inflicts a burn, poison, or paralysis to the Pokémon.",
  "Thick Fat": "The Pokémon receives half damage from Fire and Ice-type moves.",
  "Torrent": "Powers up Water-type moves when the Pokémon's HP is low.",
  "Trace": "Copies an opposing Pokémon's Ability.",
  "Truant": "The Pokémon cannot use a move two turns in a row.",
  "Vital Spirit": "The Pokémon cannot sleep.",
  "Volt Absorb": "Restores the Pokémon's HP when hit by an Electric-type move, instead of taking damage.",
  "Water Absorb": "Restores the Pokémon's HP when hit by a Water-type move, instead of taking damage.",
  "Water Veil": "The Pokémon cannot be burned.",
  "White Smoke": "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.",
  "Wonder Guard": "The Pokémon is immune to damaging moves that are not super effective.",

  //Gen IV
  "Adaptability": "Powers up moves of the same type as the Pokémon.",
  "Aftermath": "Damages the attacker if it contacts the Pokémon with a finishing hit.",
  "Anger Point": "A critical hit maxes the Pokémon's Attack stat.",
  "Anticipation": "The Pokémon can sense an opposing Pokémon's super effective moves.",
  "Bad Dreams": "Damages sleeping opposing Pokémon.",
  "Download": "Boosts the Pokémon's Attack or Sp. Atk stat based on the opposing Pokémon's Defense and Sp. Def stats.",
  "Dry Skin": "Restores the Pokémon's HP in rain, or when hit by a Water-type move. Damages the Pokémon in harsh sunlight, and increases the damage received from Fire-type moves.",
  "Filter": "Reduces the damage taken from super effective moves.",
  "Flower Gift": "Boosts the Attack and Sp. Def stats of the Pokémon and its allies in harsh sunlight.",
  "Forewarn": "The Pokémon can tell one of the moves an opposing Pokémon has.",
  "Frisk": "The Pokémon knows opposing Pokémon's held items.",
  "Gluttony": "The Pokémon eats its held Berry at half HP or less.",
  "Heatproof": "The Pokémon receives half damage from Fire-type moves.",
  "Honey Gather": "The Pokémon may gather Honey after a battle.",
  "Hydration": "Heals the Pokémon's status condition in the rain.",
  "Ice Body": "Restores the Pokémon's HP in a hailstorm.",
  "Iron Fist": "Powers up the Pokémon's punching moves.",
  "Klutz": "The Pokémon cannot use any held items.",
  "Leaf Guard": "Prevents status conditions in sunny weather.",
  "Magic Guard": "The Pokémon only takes damage from attacks.",
  "Mold Breaker": "Moves can be used on the target regardless of its Abilities.",
  "Motor Drive": "Boosts its Speed stat if hit by an Electric-type, instead of taking damage.",
  "Multitype": "Changes the Pokémon's type to match the Plate or Z-Crystal it holds.",
  "No Guard": "The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land.",
  "Normalize": "All the Pokémon's moves become Normal-type. The power of those moves is boosted a little.",
  "Poison Heal": "Restores HP if the Pokémon is poisoned, instead of losing HP.",
  "Quick Feet": "Boosts the Speed stat if the Pokémon has a status condition.",
  "Reckless": "Powers up moves that have recoil damage.",
  "Rivalry": "Becomes competitive and deals more damage to Pokémon of the same gender, but deals less to Pokémon of the opposite gender.",
  "Scrappy": "The Pokémon can hit Ghost-type Pokémon with Normal and Fighting-type moves.",
  "Simple": "The stat changes the Pokémon receives are doubled.",
  "Skill Link": "Increases the number of times multi-strike moves hit.",
  "Slow Start": "For five turns, the Pokémon's Attack and Speed stats are halved.",
  "Sniper": "Powers up moves if they become critical hits.",
  "Snow Cloak": "Boosts evasion in a hailstorm.",
  "Snow Warning": "The Pokémon summons a hailstorm when it enters a battle.",
  "Solar Power": "Boosts the Sp. Atk stat in sunny weather, but HP decreases every turn.",
  "Solid Rock": "Reduces the power of supereffective attacks taken.",
  "Stall": "The Pokémon moves after all other Pokémon do.",
  "Steadfast": "The Pokémon's determination boosts the Speed stat each time the Pokémon flinches.",
  "Storm Drain": "Draws in all Water-type moves. Instead of being hit by Water-type moves, it boosts its Sp. Atk.",
  "Super Luck": "The Pokémon is so lucky that the critical-hit ratios of its moves are boosted.",
  "Tangled Feet": "Raises evasion if the Pokémon is confused.",
  "Technician": "Powers up the Pokémon's weaker moves.",
  "Tinted Lens": "The Pokémon can use 'not very effective' moves to deal regular damage.",
  "Unaware": "When attacking, the Pokémon ignores the target Pokémon's stat changes.",
  "Unburden": "Boosts the Speed stat if the Pokémon's held item is used or lost.",

  // Gen V
  "Analytic": "Boosts move power when the Pokémon moves last.",
  "Big Pecks": "Protects the Pokémon from Defense-lowering effects.",
  "Contrary": "Makes stat changes have an opposite effect.",
  "Cursed Body": "May disable a move used on the Pokémon.",
  "Defeatist": "Halves the Pokémon's Attack and Sp. Atk stats when its HP becomes half or less.",
  "Defiant": "Boosts the Pokémon's Attack stat sharply when its stats are lowered.",
  "Flare Boost": "Powers up special attacks when the Pokémon is burned.",
  "Friend Guard": "Reduces damage done to allies.",
  "Harvest": "May create another Berry after one is used.",
  "Healer": "Sometimes heals an ally's status condition.",
  "Heavy Metal": "Doubles the Pokémon's weight.",
  "Illusion": "Comes out disguised as the Pokémon in the party's last spot.",
  "Imposter": "The Pokémon transforms itself into the Pokémon it's facing.",
  "Infiltrator": "Passes through the opposing Pokémon's barrier, substitute, and the like and strikes.",
  "Iron Barbs": "Inflicts damage to the attacker on contact with iron barbs.",
  "Justified": "Being hit by a Dark-type move boosts the Attack stat of the Pokémon, for justice.",
  "Light Metal": "Halves the Pokémon's weight.",
  "Magic Bounce": "Reflects status moves, instead of getting hit by them.",
  "Moody": "Raises one stat sharply and lowers another every turn.",
  "Moxie": "The Pokémon shows moxie, and that boosts the Attack stat after knocking out any Pokémon.",
  "Multiscale": "Reduces the amount of damage the Pokémon takes when its HP is full.",
  "Mummy": "Contact with the Pokémon changes the attacker's Ability to Mummy.",
  "Overcoat": "Protects the Pokémon from things like sand, hail, and powder.",
  "Pickpocket": "Steals an item from an attacker that made direct contact.",
  "Poison Touch": "May poison a target when the Pokémon makes contact.",
  "Prankster": "Gives priority to a status move.",
  "Rattled": "Dark, Ghost, and Bug-type moves scare the Pokémon and boost its Speed stat.",
  "Regenerator": "Restores a little HP when withdrawn from battle.",
  "Sand Force": "Boosts the power of Rock, Ground, and Steel-type moves in a sandstorm.",
  "Sand Rush": "Boosts the Pokémon's Speed stat in a sandstorm.",
  "Sap Sipper": "Boosts the Attack stat if hit by a Grass-type move, instead of taking damage.",
  "Sheer Force": "Removes additional effects to increase the power of moves when attacking.",
  "Telepathy": "Anticipates an ally's attack and dodges it.",
  "Teravolt": "Moves can be used on the target regardless of its Abilities.",
  "Toxic Boost": "Powers up physical attacks when the Pokémon is poisoned.",
  "Turboblaze": "Moves can be used on the target regardless of its Abilities.",
  "Unnerve": "Opponents cannot eat Berries.",
  "Victory Star": "Boosts the accuracy of the Pokémon and its allies.",
  "Weak Armor": "Physical attacks lower the Pokémon's Defense stat but raises its Speed stat.",
  "Wonder Skin": "Makes status moves more likely to miss.",
  "Zen Mode": "The Pokémon changes form when its HP is half or less.",

  // Gen VI
  "Aerilate": "Normal-type moves become Flying-type moves. The power of those moves is boosted a little.",
  "Aroma Veil": "Protects the Pokémon and its allies from attacks that limit their move choices.",
  "Aura Break": "Reverses the effects of Dark Aura and Fairy Aura.",
  "Bulletproof": "Protects the Pokémon from ball and bomb moves.",
  "Cheek Pouch": "Restores HP as well when the Pokémon eats a Berry.",
  "Competitive": "Boosts the Pokémon's Sp. Atk stat when a stat is lowered.",
  "Dark Aura": "Powers up every Pokémon's Dark-type moves.",
  "Delta Stream": "The Pokémon starts a mysterious air current when it enters battle.",
  "Desolate Land": "The Pokémon starts Extremely Harsh Sunlight when it enters battle.",
  "Fairy Aura": "Powers up every Pokémon's Fairy-type moves.",
  "Flower Veil": "Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats.",
  "Fur Coat": "Halves the damage from physical moves.",
  "Gale Wings": "Gives priority to Flying-type moves when the Pokémon's HP is full.",
  "Gooey": "Contact with the Pokémon lowers the attacker's Speed stat.",
  "Grass Pelt": "Boosts the Pokémon's Defense stat in Grassy Terrain.",
  "Magician": "The Pokémon steals the held item of a Pokémon it hits with a move.",
  "Mega Launcher": "Powers up aura and pulse moves.",
  "Parental Bond": "The Pokémon attacks twice.",
  "Pixilate": "Normal-type moves become Fairy-type moves. The power of those moves is boosted a little.",
  "Primordial Sea": "The Pokémon starts Heavy Rain when it enters battle.",
  "Protean": "Changes the Pokémon's type to the type of the move it's about to use.",
  "Refrigerate": "Normal-type moves become Ice-type moves. The power of those moves is boosted a little.",
  "Stance Change": "The Pokémon changes its form to Blade Form when it uses an attack move, and changes to Shield Form when it uses King's Shield.",
  "Strong Jaw": "Boosts the power of The Pokémon's biting moves.",
  "Sweet Veil": "Prevents itself and ally Pokémon from falling asleep.",
  "Symbiosis": "The Pokémon passes its item to an ally that has used up an item.",
  "Tough Claws": "Powers up moves that make direct contact.",

  // Gen VII
  "Battery": "Powers up ally Pokémon's special moves.",
  "Battle Bond": "Defeating an opposing Pokémon strengthens the Pokémon's bond with its Trainer, and it becomes Ash-Greninja. Water Shuriken gets more powerful.",
  "Beast Boost": "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.",
  "Berserk": "Boosts the Pokémon's Sp. Atk stat when it takes a hit that causes its HP to become half or less.",
  "Comatose": "It's always drowsing and will never wake up. It can attack without waking up.",
  "Corrosion": "The Pokémon can poison the target even if it's a Steel or Poison-type.",
  "Dancer": "When another Pokémon uses a dance move, it can use a dance move following it regardless of its Speed.",
  "Dazzling": "Surprises the opposing Pokémon, making it unable to attack using priority moves.",
  "Disguise": "Once per battle, the shroud that covers the Pokémon can protect it from an attack.",
  "Electric Surge": "Turns the ground into Electric Terrain when the Pokémon enters a battle.",
  "Emergency Exit": "The Pokémon, sensing danger, switches out when its HP becomes half or less.",
  "Fluffy": "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.",
  "Full Metal Body": "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.",
  "Galvanize": "Normal-type moves become Electric-type moves. The power of those moves is boosted a little.",
  "Grassy Surge": "Turns the ground into Grassy Terrain when the Pokémon enters a battle.",
  "Innards Out": "Damages the attacker landing the finishing hit by the amount equal to its last HP.",
  "Liquid Voice": "All sound-based moves become Water-type moves.",
  "Long Reach": "The Pokémon uses its moves without making contact with the target.",
  "Merciless": "The Pokémon's attacks become critical hits if the target is poisoned.",
  "Misty Surge": "Turns the ground into Misty Terrain when the Pokémon enters a battle.",
  "Neuroforce": "Powers up moves that are super effective.",
  "Power Construct": "Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Form.",
  "Power of Alchemy": "The Pokémon copies the Ability of a defeated ally.",
  "Prism Armor": "Reduces the power of supereffective attacks taken.",
  "Psychic Surge": "Turns the ground into Psychic Terrain when the Pokémon enters a battle.",
  "Queenly Majesty": "Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves.",
  "Receiver": "The Pokémon copies the Ability of a defeated ally.",
  "RKS System": "Changes the Pokémon's type to match the memory disc it holds.",
  "Schooling": "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.",
  "Shadow Shield": "Reduces the amount of damage the Pokémon takes while its HP is full.",
  "Shields Down": "When its HP becomes half or less, the Pokémon's shell breaks and it becomes aggressive.",
  "Slush Rush": "Boosts the Pokémon's Speed stat in a hailstorm.",
  "Soul-Heart": "Boosts its Sp. Atk stat every time a Pokémon faints.",
  "Stakeout": "Doubles the damage dealt to the target's replacement if the target switches out.",
  "Stamina": "Boosts the Defense stat when hit by an attack.",
  "Steelworker": "Powers up Steel-type moves.",
  "Surge Surfer": "Doubles the Pokémon's Speed stat on Electric Terrain.",
  "Tangling Hair": "Contact with the Pokémon lowers the attacker's Speed stat.",
  "Triage": "Gives priority to a healing move.",
  "Water Bubble": "Lowers the power of Fire-type moves done to the Pokémon and prevents the Pokémon from getting a burn.",
  "Water Compaction": "Boosts the Pokémon's Defense stat sharply when hit by a Water-type move.",
  "Wimp Out": "The Pokémon cowardly switches out when its HP becomes half or less.",

  // Gen VIII
  "As One (Calyrex and Glastrier)": "This Ability combines the effects of both Calyrex's Unnerve Ability and Glastrier's Chilling Neigh Ability.",
  "As One (Calyrex and Spectrier)": "This Ability combines the effects of both Calyrex's Unnerve Ability and Spectrier's Grim Neigh Ability.",
  "Ball Fetch": "If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.",
  "Chilling Neigh": "When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat.",
  "Cotton Down": "When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stat of all Pokémon except itself.",
  "Curious Medicine": "When the Pokémon enters a battle, it scatters medicine from its shell, which removes all stat changes from allies.",
  "Dauntless Shield": "Boosts the Pokémon's Defense stat when the Pokémon enters a battle.",
  "Dragon's Maw": "Powers up Dragon-type moves.",
  "Gorilla Tactics": "Boosts the Pokémon's Attack stat but only allows the use of the first selected move.",
  "Grim Neigh": "When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat.",
  "Gulp Missile": "When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.",
  "Hunger Switch": "The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of each turn.",
  "Ice Face": "The Pokémon's ice head can take a physical attack as a substitute, but the attack also changes the Pokémon's appearance. The ice will be restored when it hails.",
  "Ice Scales": "The Pokémon is protected by ice scales, which halve the damage taken from special moves.",
  "Intrepid Sword": "Boosts the Pokémon's Attack stat when the Pokémon enters a battle.",
  "Libero": "Changes the Pokémon's type to the type of the move it's about to use.",
  "Mimicry": "Changes the Pokémon's type depending on the terrain.",
  "Mirror Armor": "Bounces back only the stat-lowering effects that the Pokémon receives.",
  "Neutralizing Gas": "If the Pokémon with Neutralizing Gas is in the battle, the effects of all Pokémon's Abilities will be nullified or will not be triggered.",
  "Pastel Veil": "Protects the Pokémon and its ally Pokémon from being poisoned.",
  "Perish Body": "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.",
  "Power Spot": "Just being next to the Pokémon powers up moves.",
  "Propeller Tail": "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.",
  "Punk Rock": "Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.",
  "Quick Draw": "Enables the Pokémon to move first occasionally.",
  "Ripen": "Ripens Berries and doubles their effect.",
  "Sand Spit": "The Pokémon creates a sandstorm when it's hit by an attack.",
  "Screen Cleaner": "When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon.",
  "Stalwart": "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.",
  "Steam Engine": "Boosts the Pokémon's Speed stat drastically if hit by a Fire- or Water-type move.",
  "Steely Spirit": "Powers up ally Pokémon's Steel-type moves.",
  "Transistor": "Powers up Electric-type moves.",
  "Unseen Fist": "If the Pokémon uses moves that make direct contact, it can attack the target even if the target protects itself.",
  "Wandering Spirit": "The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact.",

  // Gen IX
  "Lingering Aroma": "Pokémon making contact with this Pokémon will have their ability changed to Lingering Aroma.",
  "Well-Baked Body": "This Pokémon takes no damage from Fire-type moves. Instead, its defense sharply increases.",
  "Seed Sower": "Turns the ground into Grassy Terrain when hit by an attack.",
  "Purifying Salt": "This Pokémon's salt protects it from status conditions and halves the effect of Ghost-type moves.",
  "Electromorphosis": "After being hit by an attack, the power of its next Electric-type move is increased.",
  "Wind Power": "This Pokémon becomes charged after being hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses. Also affected by Tailwind.",
  "Guard Dog": "Prevents the Pokémon from being forcefully swapped by enemy moves and items. The user can still swap out as normal from their own moves. If intimidated, increase attack by one stage instead.",
  "Wind Rider": "Boosts this Pokémon's attack when Tailwind takes effect or when hit by a wind move. This Pokémon takes no damage from wind moves.",
  "Mycelium Might": "The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the ability of the target.",
  "Anger Shell": "When the user's HP drops to 50% or lower, its defense and special defense drop by one stage, but the user's attack, special attack and speed increase by one stage.",
  "Opportunist": "If an opponent's stats are boosted, the Pokémon seizes the opportunity to boost the same stat for itself.",
  "Rocky Payload": "Powers up Rock-type moves.",
  "Zero to Hero": "This Pokémon switches to Hero Forme when it switches out.",
  "Earth Eater": "If hit by a Ground-type move, the Pokémon heals instead of taking damage.",
  "Toxic Debris": "The Pokémon scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.",
  "Costar": "When this Pokémon switches in, it copies ally stat changes for itself.",
  "Sharpness": "Boosts the effect of this Pokémon's cutting moves.",
  "Commander": "When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo and issues commands from there.",
  "Armor Tail": "Prevents opposing Pokémon from using priority moves against the target.",
  "Cud Chew": "After using a berry, it will use it again to the same effect at the end of the trainer's turn.",
  "Supreme Overlord": "This Pokémon receives a 10% additive increase to the power of their moves for each ally Pokémon that is fainted in their party.",
  "Protosynthesis": "If the Pokémon is holding Booster Energy or the current weather is Harsh Sunlight, the Pokémon will boost their most proficient stat by one stage.",
  "Quark Drive": "If the Pokémon is holding Booster Energy or Electric Terrain is active, the Pokémon will boost their most proficient stat by one stage.",
  "Thermal Exchange": "Boosts the attack stat when the Pokémon is hit by a Fire-type move. This Pokémon also cannot be burned.",
  "Good as Gold": "A body of pure, solid gold gives the Pokémon full immunity to other Pokémon's status moves.",
  "Tablets of Ruin": "This Pokémon lowers the attack of all Pokémon except Wo-Chien.",
  "Sword of Ruin": "This Pokémon lowers the defense of all Pokémon except Chien-Pao.",
  "Vessel of Ruin": "This Pokémon lowers the special attack of all Pokémon except Ting-Lu.",
  "Beads of Ruin": "This Pokémon lowers the special defense of all Pokémon except Chi-Yu.",
  "Orichalcum Pulse": "Turns the sunlight harsh when the Pokémon enters the battle. The ancient pulse thrumming through the Pokémon also boosts its attack in Harsh Sunlight.",
  "Hadron Engine": "Turns the ground into Electric Terrain when the Pokémon enters the battle. The futuristic engine within the Pokémon also boosts its special attack on Electric Terrain.",
  "Embody Aspect": "The Pokémon's heart fills with memories, causing the (corresponding mask) to shine and the Pokémon's Speed/Defense/Attack/Special Defense stat to be boosted.",
  "Toxic Chain": "All of this Pokémon's moves have a 30% chance to badly poison the target.",
  "Hospitality": "Upon a switch, this Pokémon heals a small amount of its ally's HP.",
  "Supersweet Syrup": "This Pokémon lowers its opponent's evasiveness upon switch-in.",
  "Mind's Eye": "This Pokémon is immune to accuracy drops, opponent's evasiveness boosts, and can hit Ghost-types with Normal- and Fighting-type moves.",
  "Poison Puppeteer": "This Pokémon confuses any Pokémon it poisons.",

  // Lacadia
  "Parasitoid": { description: "This Pokémon's HP-draining moves have their HP recovery boosted by 30%.", tag: "lacadia" },
  "Ancient Guard": { description: "Rock-type moves are not very effective against this Pokémon and it is also immune to Stealth Rock.", tag: "lacadia" },
  "Pollyanna": { description: "Raises this Pokémon's HP when hit by a Dark-type move, instead of taking damage.", tag: "lacadia" },
  "Overload": { description: "This Pokémon skips charge and recharge turns for moves.", tag: "lacadia" },
  "Stoicism": { description: "This Pokémon is immune to attack drops, burns, and flinches.", tag: "lacadia" },
  "Lockdown": { description: "This Pokémon is immune to pivot moves and blocks switch effects.", tag: "lacadia" },
  "Withering": { description: "Prevents all Pokémon from restoring health.", tag: "lacadia" },
  "Verdant Hunger": { description: "The power of draining moves and Leech Seed is doubled.", tag: "lacadia" },
  "Polarity": { description: "This Pokémon's Fire-type moves become slightly more powerful in snow, and its Ice-type moves become slightly more powerful in harsh sunlight.", tag: "lacadia" },
  "Noble Bearing": { description: "Boosts defense, special defense, and speed when this Pokémon successfully inflicts a status condition.", tag: "lacadia" },
  "Caffeine Rush": { description: "When the user's HP drops to 50% or lower, it restores a quarter of its health and maxes its Speed stat.", tag: "lacadia" },
  "Ruthless": { description: "This Pokémon's attacks always result in critical hits when the opponent has lowered stats.", tag: "lacadia" },
  "Malodorous": { description: "When this Pokémon is knocked out in battle, the opposing Pokémon has its stats lowered by one stage.", tag: "lacadia" },
  "Schrödinger": { description: "This Pokémon's normal type moves become ghost type, and vice versa.", tag: "lacadia" },
  "Surveil": { description: "When it enters a battle, the Pokémon can tell the speed stat of the opposing Pokémon.", tag: "lacadia" },
  "Backstabber": { description: "This Pokémon's attack moves will always hit a target first if that target is switching out of battle.", tag: "lacadia" },
  "Meltdown": { description: "This Pokémon will use the move Eruption immediately after being hit by a Fire-type move.", tag: "lacadia" },
  "Metal Eater": { description: "This Pokémon's moves become 30% more powerful when a Steel-type Pokémon is on the field.", tag: "lacadia" },
  "Momentum": { description: "This Pokémon's attack moves become more powerful each time they are used consecutively.", tag: "lacadia" },
  "Hunter's Instincts": { description: "When this Pokémon or an opposing Pokémon enters the battle, the Pokémon reveals whether the opponent can be knocked out in one hit.", tag: "lacadia" },
  "Abrasive": { description: "When it enters battle, this Pokémon deals damage equal to one-eighth of the enemy's max HP.", tag: "lacadia" },
  "Lucky Star": { description: "This Pokémon's moves have a doubled chance of triggering secondary effects, while the opponent's moves have a half chance of triggering secondary effects on the user.", tag: "lacadia" },
  "Aspect Twist": { description: "This Pokémon's Physical moves use its Sp. Atk stat, while Special moves use the Atk stat.", tag: "lacadia" },
  "Brain Jack": { description: "This Pokémon's Psychic-type moves have a 50% chance of inflicting confusion, infatuation, disable, encore, or torment.", tag: "lacadia" },
  "Flightless": { description: "Powers up Flying-type moves.", tag: "lacadia" },
  "Life Aurora": { description: "Whenever an opposing Pokémon restores health, this Pokémon restores the same amount of health.", tag: "lacadia" },
  "Inrush Current": { description: "If the user's previous move has failed, the power of its next move doubles.", tag: "lacadia" },
  "Vitrified": { description: "Boosts its and its ally's special defense stat the first time the Pokémon enters a battle.", tag: "lacadia" },
  "Decay": { description: "All non-Ghost and Dark type Pokémon lose 1/16 of their max HP at the end of each turn.", tag: "lacadia" },
  "Honor-Bound Duel": { description: "Doubles the damage dealt to the target's replacement if the target switches out.", tag: "lacadia" },
  "Circle of Protection": { description: "The Pokémon takes half damage from moves with a base power of 100 or higher.", tag: "lacadia" },
    "Stealth Strike": { description: "Semi-invulnerable moves deal 50% more damage, and deal 100% more damage if the target switches.", tag: "lacadia" },
  "Weight of the World": { description: "The Pokémon starts the effects of Gravity when it enters battle.", tag: "lacadia" },
    "Cry of the Cosmos": { description: "The Pokémon's presence allows Dark type Pokémon to be hit with Psychic type moves and doubles the chance all moves have an additional effect.", tag: "lacadia" },
    "Hoarder": { description: "The Pokémon gives a copy of its held item to it and its allies.", tag: "lacadia" },
    "Bell of Ruin": { description: "The Pokémon's bell rings when its HP becomes half or less. Then the Pokémon changes its form to Dirge Form.", tag: "lacadia"},
    "Dominion": { description: "While the Pokémon is in the battle, the effects of all other Pokémon's Abilities will be nullified or will not be triggered.", tag: "lacadia"},
    "Manifestation": { description: "Boosts the Pokémon's most proficient stat the first time the Pokémon enters a battle.", tag: "lacadia"},





}
